### ISSUE TITLE
无痕跳出验证问题

### ISSUE THREAD

**Issue by Worryfrees** [JDHelloWorld/jd_price#1]
https://m.gwdang.com/weixin/compare/0?from=shortcut&origin_url=https://item.m.jd.com/product/100001795039.html? 无痕模式会出现验证码，在访问这个链接一次会出现历史价格，大佬您看看

**Comment by JDHelloWorld** [comment]
不用gwdang了

**Comment by Worryfrees** [comment]
好吧
